stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/prepared.csv
  featurize:
    cmd: python src/featurize.py
    deps:
      - src/featurize.py
      - data/prepared.csv
    params:
      - featurize
    outs:
      - data/features.csv
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/features.csv
    params:
      - train
    metrics:
      - metrics/scores.json:
          cache: false
